%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-cob-command-tools
Version:        0.6.15
Release:        1%{?dist}
Summary:        ROS cob_command_tools package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_command_tools
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-cob-command-gui
Requires:       ros-melodic-cob-dashboard
Requires:       ros-melodic-cob-helper-tools
Requires:       ros-melodic-cob-interactive-teleop
Requires:       ros-melodic-cob-monitoring
Requires:       ros-melodic-cob-script-server
Requires:       ros-melodic-cob-teleop
BuildRequires:  ros-melodic-catkin

%description
The cob_command_tools stack provides tools, for operating Care-O-bot.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Thu Nov 07 2019 Felix Messmer <felixmessmer@gmail.com> - 0.6.15-1
- Autogenerated by Bloom

* Wed Aug 07 2019 Felix Messmer <felixmessmer@gmail.com> - 0.6.14-1
- Autogenerated by Bloom

